[package]
name = "rex"
version = "0.1.2"
authors = [
    "Christopher Breeden <github@u.breeden.cc>",
    "Sebastian Köln <s3bk@protonmail.com>"
]
edition = "2021"

[dependencies]
ttf-parser = "0.15"
unicode-math = { git = "https://github.com/s3bk/unicode-math/" }
itertools = "0.9"
nom = "5.1"
