[package]
name = "rex"
version = "0.1.2"
authors = [
    "Christopher Breeden <github@u.breeden.cc>",
    "Sebastian Köln <s3bk@protonmail.com>"
]
edition = "2018"

[dependencies]
font = { git = "https://github.com/pdf-rs/font" }
unicode-math = { git = "https://github.com/s3bk/unicode-math/" }
